import bpy

from .panels import WorkflowGatedPanel, _draw_wrapped_text, active_role_collection, object_section_visible

# The fixed rung each LOD slot lands on, read off every game-ready model (PLAN_vegetation.md 1.6).
# Shown next to a LOD whose own file did not record one, so an imported model and a hand-made
# collection describe themselves the same way.
LOD_CAMERA_DISTANCES = (100.0, 200.0, 400.0, 500.0)


def _distance_label(collection: bpy.types.Collection, lod_number: int | None) -> str:
    distance = collection.get("tw_lod_camera_distance")
    if distance is None and lod_number is not None and lod_number <= len(LOD_CAMERA_DISTANCES):
        distance = LOD_CAMERA_DISTANCES[lod_number - 1]
    return f"out to {distance:g}m" if distance is not None else "no camera distance recorded"


def _lod_number(collection: bpy.types.Collection) -> int | None:
    tail = collection.name.rsplit(" ", 1)[-1]
    return int(tail) if tail.isdigit() else None


class TW_PT_vegetation_setup(WorkflowGatedPanel, bpy.types.Panel):
    bl_label = "Vegetation"
    bl_idname = "TW_PT_vegetation_setup"
    bl_space_type = "VIEW_3D"
    bl_region_type = "UI"
    bl_category = "Total War"
    bl_order = 1
    workflows = frozenset({"VEGETATION"})

    def draw(self, context: bpy.types.Context) -> None:
        layout = self.layout
        model = active_role_collection(context, object_section_visible(context), "VEGETATION")
        if model is None:
            _draw_wrapped_text(
                layout,
                "Import a tree, shrub or stone with File > Import - either its .rigid_model_v2, "
                "which pulls in its _tech.cs2.parsed too, or that sidecar on its own.",
            )
            return

        box = layout.box()
        box.label(text=model.name, icon="OUTLINER_COLLECTION")
        bone_table = model.get("tw_bone_table_name")
        if bone_table:
            box.label(text=f"Skeleton: {bone_table}", icon="ARMATURE_DATA")

        for child in model.children:
            row = layout.box()
            if child.tw_role == "VEGETATION_LOD":
                row.label(text=child.name, icon="MESH_DATA")
                row.label(text=f"{_distance_label(child, _lod_number(child))}, {len(child.objects)} mesh(es)")
            elif child.tw_role == "VEGETATION_BILLBOARD":
                row.label(text=child.name, icon="IMAGE_PLANE")
                row.label(text=f"{_distance_label(child, None)}, generated by BOB")
            elif child.tw_role == "VEGETATION_FIRE":
                row.label(text=child.name, icon="OUTLINER_OB_FORCE_FIELD")
                emitters = sum(len(obj.data.vertices) for obj in child.objects if obj.get("tw_vfx_action"))
                row.label(text=f"{emitters} fire emitter(s), generated by BOB")

        _draw_wrapped_text(
            layout,
            "The billboard and the fire hull are BOB's output, not source: it builds the hull from "
            "the lowest LOD and spreads the emitters over it. Editing them changes nothing.",
        )
        layout.label(text="Import only - no vegetation export yet", icon="INFO")


CLASSES = (TW_PT_vegetation_setup,)


def register() -> None:
    for cls in CLASSES:
        bpy.utils.register_class(cls)


def unregister() -> None:
    for cls in reversed(CLASSES):
        bpy.utils.unregister_class(cls)
